"""Download Google Fonts locally so the browser never contacts fonts.googleapis.com
or fonts.gstatic.com (GDPR: no user IP sent to a third country).

Keeps only the latin / latin-ext subsets, rewrites url() to a local relative path
and writes one CSS file per page under static/vendor/fonts/.
"""
import os, re, sys, urllib.request

OUT_DIR = sys.argv[1]
FONT_DIR = os.path.join(OUT_DIR, "fonts")
os.makedirs(FONT_DIR, exist_ok=True)

# Modern UA => woff2. Without it Google serves ttf.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

PAGES = {
    "login": "https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Syne:wght@600;700;800&display=swap",
    "traveller": "https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&display=swap",
    "admin": "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap",
}

KEEP_SUBSETS = {"latin", "latin-ext"}


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


total_files = 0
for page, url in PAGES.items():
    css = fetch(url)
    # Google emits:  /* latin */\n@font-face { ... }
    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    if not blocks:
        sys.exit(f"No @font-face blocks parsed for {page}")

    out_css = [f"/* Self-hosted Google Fonts for {page} — generated by tools/vendor_fonts.py.",
               "   Do not edit by hand. Fonts are served from our own origin so that no",
               "   user IP address is disclosed to Google (GDPR art. 44 ss.). */", ""]

    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*([\w\s]+);", block).group(1).strip()
        style = re.search(r"font-style:\s*(\w+);", block)
        style = style.group(1) if style else "normal"
        src = re.search(r"url\((https://[^)]+)\)", block).group(1)

        fname = f"{slug(family)}-{slug(weight)}-{style}-{subset}.woff2"
        path = os.path.join(FONT_DIR, fname)
        if not os.path.exists(path):
            with open(path, "wb") as fh:
                fh.write(fetch(src, binary=True))
            total_files += 1

        local = block.replace(src, fname)
        # keep the subset marker as a comment for maintainability
        out_css.append(f"/* {family} {weight} {style} — {subset} */")
        out_css.append(local.strip())
        out_css.append("")

    with open(os.path.join(FONT_DIR, f"{page}-fonts.css"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out_css))
    print(f"{page}: written {page}-fonts.css")

print(f"downloaded {total_files} woff2 files into {FONT_DIR}")
